from pathlib import Path
import re

p=Path('index.html')
s=p.read_text()
old=re.search(r'async function raids\(\)\{.*?\n\}\nasync function wild\(\)',s,re.S)
if not old:
    raise SystemExit('raids function not found')

new=r'''async function raids(){let b=$('raids');try{let raw=await get(U.raids,60000),n=[],sh=[];Object.entries(raw||{}).forEach(([g,ls])=>(Array.isArray(ls)?ls:[]).forEach(r=>(/^Shadow/i.test(r.name)?sh:n).push({...r,g})));let tier=r=>{let t=String(r.tier||r.g||'').toLowerCase();return t.includes('mega')?'Mega':t.includes('5')?'5-stjernet':t.includes('3')?'3-stjernet':'1-stjernet'},players=r=>r.recommended_players??r.recommendedPlayers??r.min_players??r.minPlayers??(tier(r)==='Mega'?'5+':tier(r)==='5-stjernet'?'4–6':tier(r)==='3-stjernet'?'2–3':'1'),draw=r=>`<div class="card click" data-r="${encodeURIComponent(JSON.stringify(r))}"><div class=row><div class=img>${r.asset_url?`<img src="${E(r.asset_url)}">`:'⚔️'}</div><div class=grow><div class=name>${E(r.name)}</div><div class=small>${E((r.types||[]).join(' · '))} · ${r.shiny_available===true?'✨ Shiny mulig':'Shiny ikke angivet'}</div></div>›</div><div class=stats><div class=stat><b>${players(r)}</b><span>Spillere</span></div><div class=stat><b>${r.cp_range?.max??'—'}</b><span>Hundo CP</span></div><div class=stat><b>${r.boosted_cp_range?.max??'—'}</b><span>Boost hundo</span></div></div></div>`;let group=(arr)=>{let h='';['1-stjernet','3-stjernet','5-stjernet','Mega'].forEach(t=>{let q=arr.filter(r=>tier(r)===t);if(q.length)h+=`<div class=section>${t}</div>`+q.map(draw).join('')});return h};b.innerHTML=`<div class="raid-tabs"><button class="raid-tab active" data-raid-tab="normal">Mega / normale</button><button class="raid-tab" data-raid-tab="shadow">Shadow</button></div><div id="raid-normal">${group(n)}</div><div id="raid-shadow" style="display:none">${group(sh)}</div>`;let tabs=b.querySelectorAll('[data-raid-tab]');tabs.forEach(x=>x.onclick=()=>{let shadow=x.dataset.raidTab==='shadow';tabs.forEach(t=>t.classList.toggle('active',t===x));$('raid-normal').style.display=shadow?'none':'';$('raid-shadow').style.display=shadow?'':'none'});b.querySelectorAll('[data-r]').forEach(x=>x.onclick=()=>{let r=JSON.parse(decodeURIComponent(x.dataset.r)),c=SP[r.name]||CT[(r.types||[])[0]]||['Ikke oplyst',[],[]];open(`<h2>${E(r.name)}</h2><div class=small>${players(r)} spillere</div><div class=section>Type</div><div class=card>${E((r.types||[]).join(' · ')||'Ikke oplyst')}</div><div class=section>Gode mod den</div><div class=card><b>Svag mod:</b> ${E(c[0])}<div class=section>Mega / Primal</div>${c[1].map(v=>`<div class=small>• ${E(v)}</div>`).join('')}<div class=section>Ikke Mega</div>${c[2].map(v=>`<div class=small>• ${E(v)}</div>`).join('')}</div><div class=stats><div class=stat><b>${r.cp_range?.max??'—'}</b><span>Hundo CP</span></div><div class=stat><b>${r.boosted_cp_range?.max??'—'}</b><span>Boost hundo</span></div><div class=stat><b>${r.shiny_available===true?'Mulig':'Ikke angivet'}</b><span>Shiny</span></div></div>`)});up()}catch(e){b.innerHTML='<div class=note>Kunne ikke hente raids.</div>'}}
async function wild(){'''
s=s[:old.start()]+new+s[old.end():]
css='''.raid-tabs{display:flex;gap:8px;margin:0 0 12px}.raid-tab{flex:1;padding:10px 8px;border:1px solid var(--l);border-radius:12px;background:var(--c);color:var(--m);font-weight:800}.raid-tab.active{background:var(--y);color:#111}'''
s=s.replace('</style></head>','</style><style id="raid-tabs-css">'+css+'</style></head>',1)
p.write_text(s)
'''
